import { EmojiPicker } from '../components/EmojiPicker';
import { ToolbarConfig } from '../types/toolbar';

export const defaultToolbar: ToolbarConfig = {
  position: 'bottom',
  visible: true,
  groups: [
    {
      type: 'rich-text',
      name: 'history',
      position: 1,
      hidden: false,
      dropdown: true,
      align: 'left',
      commands: [
        {
          name: 'undo',
          position: 1,
          hidden: false,
          icon: 'undo',
        },
        {
          name: 'redo',
          position: 2,
          hidden: false,
          icon: 'redo',
        },
      ],
    },
    {
      type: 'rich-text',
      name: 'inline',
      position: 2,
      hidden: false,
      dropdown: false,
      align: 'left',
      commands: [
        {
          name: 'bold',
          position: 1,
          hidden: false,
          icon: 'bold',
        },
        {
          name: 'italic',
          position: 2,
          hidden: false,
          icon: 'italic',
        },
        {
          name: 'underline',
          position: 3,
          hidden: false,
          icon: 'underline',
        },
        {
          name: 'strikethrough',
          position: 4,
          hidden: false,
          icon: 'strikethrough',
        },
      ],
    },
    {
      type: 'rich-text',
      name: 'alignment',
      position: 3,
      hidden: false,
      dropdown: true,
      align: 'left',
      commands: [
        { name: 'left', position: 1, hidden: false, icon: 'align-left' },
        { name: 'center', position: 2, hidden: false, icon: 'align-center' },
        { name: 'right', position: 3, hidden: false, icon: 'align-right' },
        { name: 'justify', position: 4, hidden: false, icon: 'align-justify' },
        { name: 'start', position: 5, hidden: false, icon: 'align-left' },
        { name: 'end', position: 6, hidden: false, icon: 'align-right' },
        { name: 'outdent', position: 7, hidden: false, icon: 'indent-left' },
        { name: 'indent', position: 8, hidden: false, icon: 'indent-right' },
      ],
    },
    {
      type: 'rich-text',
      name: 'block',
      position: 4,
      hidden: false,
      dropdown: true,
      align: 'left',
      commands: [
        {
          name: 'normal',
          position: 1,
          hidden: false,
          icon: 'clear-formatting',
        },
        { name: 'heading 1', position: 2, hidden: false, icon: 'heading-h1' },
        { name: 'heading 2', position: 3, hidden: false, icon: 'heading-h2' },
        { name: 'heading 3', position: 4, hidden: false, icon: 'heading-h3' },
        { name: 'heading 4', position: 5, hidden: false, icon: 'heading-h4' },
        { name: 'heading 5', position: 6, hidden: false, icon: 'heading-h5' },
        { name: 'heading 6', position: 7, hidden: false, icon: 'heading-h6' },
        { name: 'blockquote', position: 8, hidden: false, icon: 'quote-right' },
        { name: 'code', position: 8, hidden: false, icon: 'code' },
      ],
    },
    {
      type: 'rich-text',
      name: 'list',
      position: 5,
      hidden: false,
      dropdown: false,
      align: 'left',
      commands: [
        { name: 'ordered', position: 1, hidden: false, icon: 'list-number' },
        {
          name: 'unordered',
          position: 2,
          hidden: false,
          icon: 'list-bullet',
        },
        { name: 'outdent', position: 3, hidden: false, icon: 'indent-left' },
        { name: 'indent', position: 4, hidden: false, icon: 'indent-right' },
      ],
    },
    {
      type: 'rich-text',
      name: 'link',
      position: 6,
      hidden: false,
      dropdown: false,
      align: 'left',
      commands: [
        { name: 'link', position: 1, hidden: false, icon: 'link' },
        { name: 'unlink', position: 2, hidden: false, icon: 'unlink' },
      ],
    },
    {
      type: 'custom-component',
      name: 'emoji-picker',
      position: 1,
      hidden: false,
      align: 'right',
      dropdown: false,
      renderComponent: <EmojiPicker />,
    },
  ],
};
