export default {
    code: 'lp-editor-code',
    heading: {
        h1: 'lp-editor-heading-h1',
        h2: 'lp-editor-heading-h2',
        h3: 'lp-editor-heading-h3',
        h4: 'lp-editor-heading-h4',
        h5: 'lp-editor-heading-h5',
        h6: 'lp-editor-heading-h6',
    },
    image: 'editor-image',
    indent: 'lp-indent',
    link: 'editor-link',
    list: {
        listitem: 'editor-listitem',
        nested: {
            listitem: 'editor-nested-listitem',
        },
        ol: 'editor-list-ol',
        ul: 'editor-list-ul',
    },
    ltr: 'ltr',
    paragraph: 'lp-editor-paragraph',
    placeholder: 'editor-placeholder',
    quote: 'lp-editor-quote',
    rtl: 'rtl',
    text: {
        bold: 'lp-editor-text-bold',
        code: 'lp-editor-text-code',
        hashtag: 'lp-editor-text-hashtag',
        italic: 'lp-editor-text-italic',
        strikethrough: 'lp-editor-text-strikethrough',
        underline: 'lp-editor-text-underline',
        underlineStrikethrough: 'lp-editor-text-underline-strikethrough',
        subscript: 'lp-text-subscript',
        superscript: 'lp-text-superscript',
    },
};